/*
 * ORFpred - © Damian Bolwerk, Jonathan Feenstra, Fini De Gruyter, Lotte Houwen 
 * & Alex Janse.
 * Functie: Open Reading Frames voorspellen in DNA sequenties.
 * 
 */
package orfpred;

/**
 *
 * @author Jonathan Feenstra
 * @since JDK 1.8
 * @version 1.0
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seqModeGroup = new javax.swing.ButtonGroup();
        headerLabel = new javax.swing.JLabel();
        headerSeparator = new javax.swing.JSeparator();
        mainPanel = new javax.swing.JPanel();
        seqLabel = new javax.swing.JLabel();
        seqScrollPane = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        blastLabel = new javax.swing.JLabel();
        blastScrollPane = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        orfButton = new javax.swing.JButton();
        headerComboBox = new javax.swing.JComboBox<>();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        openMenuItem = new javax.swing.JMenuItem();
        dbSaveMenuItem = new javax.swing.JMenuItem();
        menuSeparator1 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        viewMenu = new javax.swing.JMenu();
        seqModeMenu = new javax.swing.JMenu();
        protRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        dnaRadioButtonMenuItem = new javax.swing.JRadioButtonMenuItem();
        highlightMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        blastMenuItem = new javax.swing.JMenuItem();
        orfLengthMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORFpred - Open Reading Frame prediction tool");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/orfpred.png")).getImage());
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 500));

        headerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/header.png"))); // NOI18N
        headerLabel.setToolTipText("");
        headerLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(headerLabel, java.awt.BorderLayout.PAGE_START);

        headerSeparator.setName(""); // NOI18N
        getContentPane().add(headerSeparator, java.awt.BorderLayout.CENTER);

        seqLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        seqLabel.setText("Sequence");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        seqScrollPane.setViewportView(jTextArea1);

        blastLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        blastLabel.setText("BLAST results");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable1.setRequestFocusEnabled(false);
        blastScrollPane.setViewportView(jTable1);

        orfButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/search.png"))); // NOI18N
        orfButton.setText("Find ORF's");

        headerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<FASTA headers appear here after opening a file>" }));
        headerComboBox.setEnabled(false);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(blastScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addComponent(seqScrollPane, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(blastLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mainPanelLayout.createSequentialGroup()
                        .addComponent(seqLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(headerComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(orfButton)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seqLabel)
                    .addComponent(orfButton)
                    .addComponent(headerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(seqScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blastLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(blastScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(mainPanel, java.awt.BorderLayout.PAGE_END);

        fileMenu.setText("File");

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open.png"))); // NOI18N
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);

        dbSaveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        dbSaveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/database.png"))); // NOI18N
        dbSaveMenuItem.setText("Save to Database");
        fileMenu.add(dbSaveMenuItem);
        fileMenu.add(menuSeparator1);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exit.png"))); // NOI18N
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        viewMenu.setText("View");

        seqModeMenu.setText("Sequence mode");

        seqModeGroup.add(protRadioButtonMenuItem);
        protRadioButtonMenuItem.setSelected(true);
        protRadioButtonMenuItem.setText("Protein");
        protRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                protRadioButtonMenuItemActionPerformed(evt);
            }
        });
        seqModeMenu.add(protRadioButtonMenuItem);

        seqModeGroup.add(dnaRadioButtonMenuItem);
        dnaRadioButtonMenuItem.setText("DNA");
        dnaRadioButtonMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnaRadioButtonMenuItemActionPerformed(evt);
            }
        });
        seqModeMenu.add(dnaRadioButtonMenuItem);

        viewMenu.add(seqModeMenu);

        highlightMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/highlight.png"))); // NOI18N
        highlightMenuItem.setText("Highlight colour");
        highlightMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highlightMenuItemActionPerformed(evt);
            }
        });
        viewMenu.add(highlightMenuItem);

        menuBar.add(viewMenu);

        jMenu1.setText("Options");

        blastMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blast.png"))); // NOI18N
        blastMenuItem.setText("BLAST whole sequence");
        blastMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blastMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(blastMenuItem);

        orfLengthMenuItem.setText("Set minimum ORF length");
        orfLengthMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orfLengthMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(orfLengthMenuItem);

        menuBar.add(jMenu1);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        FileHandler.loadFile(headerComboBox);
    }//GEN-LAST:event_openMenuItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void dnaRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnaRadioButtonMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnaRadioButtonMenuItemActionPerformed

    private void protRadioButtonMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_protRadioButtonMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_protRadioButtonMenuItemActionPerformed

    private void highlightMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highlightMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_highlightMenuItemActionPerformed

    private void blastMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blastMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blastMenuItemActionPerformed

    private void orfLengthMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orfLengthMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orfLengthMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blastLabel;
    private javax.swing.JMenuItem blastMenuItem;
    private javax.swing.JScrollPane blastScrollPane;
    private javax.swing.JMenuItem dbSaveMenuItem;
    private javax.swing.JRadioButtonMenuItem dnaRadioButtonMenuItem;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JComboBox<String> headerComboBox;
    private javax.swing.JLabel headerLabel;
    private javax.swing.JSeparator headerSeparator;
    private javax.swing.JMenuItem highlightMenuItem;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPopupMenu.Separator menuSeparator1;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JButton orfButton;
    private javax.swing.JMenuItem orfLengthMenuItem;
    private javax.swing.JRadioButtonMenuItem protRadioButtonMenuItem;
    private javax.swing.JLabel seqLabel;
    private javax.swing.ButtonGroup seqModeGroup;
    private javax.swing.JMenu seqModeMenu;
    private javax.swing.JScrollPane seqScrollPane;
    private javax.swing.JMenu viewMenu;
    // End of variables declaration//GEN-END:variables
}
